<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/css" 
href="1.css"?>
<!DOCTYPE FACULTY [
<!ELEMENT FACULTY (NAME, TIME, EXAM, PAGES, PASSING)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT TIME (#PCDATA)>
<!ELEMENT EXAM (#PCDATA)>
<!ELEMENT PAGES (#PCDATA)>
<!ELEMENT PASSING (#PCDATA)>
]>

<FACULTY>
<NAME> Касперский </NAME>
<TIME> 11:00 </TIME>
<EXAM> ТРПО </EXAM>
<PAGES> 92-98 </PAGES>
<PASSING> Ауд. 302-3 </PASSING>

<NAME> Andry </NAME>
<TIME> 11:30 </TIME>
<EXAM> ОАиП </EXAM>
<PAGES> 102-107 </PAGES>
<PASSING> Ауд. 12-1 </PASSING>
</FACULTY>